import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import sharp from 'sharp';
test.use({actionTimeout:15000});

async function login(page){await page.goto('/admin/login');await page.getByLabel('Username').fill('browser-editor');await page.getByLabel('Password',{exact:true}).fill('browser-test-only-password-2026');await page.getByRole('button',{name:'Sign in'}).click();await expect(page).toHaveURL(/\/admin$/);}
async function panel(page,id){await page.goto('/admin#'+id);await expect(page.locator('#'+id)).toBeVisible();}
async function confirm(page){await expect(page.locator('#confirm-dialog')).toBeVisible();await page.locator('#confirm-dialog [value="confirm"]').click();}
async function saved(page,text='Content saved.'){await expect(page.locator('#studio-notice')).toContainText(text);}
async function imageFile(name,color){return {name,mimeType:'image/png',buffer:await sharp({create:{width:640,height:480,channels:3,background:color}}).png().toBuffer()};}
async function skip(page){const intro=page.locator('#intro');if(await intro.isVisible())await page.keyboard.press('Escape');}
async function noOverflow(page){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
async function axe(page,include){let builder=new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']);if(include)builder=builder.include(include);const result=await builder.analyze();expect(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))).toEqual([]);}

test('premium public pages, navigation, responsive layouts and real galleries are accessible',async({page,isMobile},info)=>{
  test.setTimeout(150000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
  for(const route of ['/','/about','/events','/team','/join','/contact']){
    await page.goto(route);await skip(page);await expect(page.locator('h1')).toBeVisible();await noOverflow(page);
    await page.locator('footer').scrollIntoViewIfNeeded();await axe(page);
    const internal=await page.locator('header a,footer a').evaluateAll(links=>[...new Set(links.map(link=>link.getAttribute('href')).filter(href=>href?.startsWith('/')&&!href.startsWith('//')))]);
    for(const href of internal)expect((await page.request.get(href)).status()).toBe(200);
  }
  const events=await (await page.request.get('/api/events')).json();
  for(const event of events){
    await page.goto('/events/'+event.id);await noOverflow(page);
    const gallery=page.locator('[data-stack-gallery]'),deck=gallery.locator('.stack-deck');const photos=event.gallery.length?event.gallery:event.image?[event.image]:[];
    await expect(gallery.locator('.gallery-slide:not([hidden]) img')).toBeVisible();await expect.poll(()=>gallery.locator('.gallery-slide:not([hidden]) img').evaluate(el=>el.complete&&el.naturalWidth>0)).toBe(true);
    if(photos.length>1){
      await gallery.getByRole('button',{name:'Next photograph'}).click();await expect(gallery).toHaveAttribute('data-selected','1');
      await gallery.getByRole('button',{name:'Previous photograph'}).click();await expect(gallery).toHaveAttribute('data-selected','0');
      await deck.focus();await page.keyboard.press('ArrowRight');await expect(gallery).toHaveAttribute('data-selected','1');
      await gallery.getByRole('button',{name:'Show photograph 1',exact:true}).click();await expect(gallery).toHaveAttribute('data-selected','0');
      const box=await deck.boundingBox();
      if(!isMobile){await deck.click({position:{x:box.width*.75,y:box.height*.65}});await expect(gallery).toHaveAttribute('data-selected','1');await page.mouse.move(box.x+box.width*.7,box.y+box.height*.35);await expect(gallery).toHaveClass(/card-hovering/);await page.mouse.move(1,1);await expect(gallery).toHaveAttribute('data-selected','1');}
      else{await deck.scrollIntoViewIfNeeded();const rect=await deck.boundingBox(),cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect.x+rect.width*.8,y:rect.y+rect.height*.45}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:rect.x+rect.width*.2,y:rect.y+rect.height*.45}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();await expect(gallery).toHaveAttribute('data-selected','1');}
      await page.emulateMedia({reducedMotion:'reduce'});await expect(gallery.locator('.gallery-slide:not([hidden])')).toHaveCSS('transform','none');await page.emulateMedia({reducedMotion:'no-preference'});
    }
  }
  await page.goto('/events');await expect(page.locator('.event-image')).toHaveCount(0);await page.getByRole('button',{name:/View PROMPT.*gallery/}).click();await expect(page.locator('#detail-dialog .gallery-slide:not([hidden]) img')).toBeVisible();await page.keyboard.press('Escape');await page.goto('/#events');await page.getByRole('button',{name:/View PROMPT.*gallery/}).click();await axe(page,'#detail-dialog');await noOverflow(page);await page.screenshot({path:`test-results/premium-gallery-${info.project.name}.png`});await page.keyboard.press('Escape');await expect(page.locator('#detail-dialog')).not.toBeVisible();
  await page.goto('/');await skip(page);await page.screenshot({path:`test-results/premium-home-${info.project.name}.png`,fullPage:true});
  if(!isMobile){for(const width of [820,1024,1366]){await page.setViewportSize({width,height:900});await noOverflow(page);}await page.setViewportSize({width:1280,height:720});}
  expect(errors).toEqual([]);
});

test('admin event editor uploads, orders, previews, publishes and deletes events securely',async({page,isMobile},info)=>{
  test.setTimeout(150000);const errors=[];page.on('pageerror',error=>errors.push(error.message));await login(page);await noOverflow(page);await axe(page);await page.screenshot({path:`test-results/premium-admin-${info.project.name}.png`,fullPage:true});
  await expect(page.locator('.site-header')).toHaveCount(0);await expect(page.locator('header').getByText('Join CIPHER')).toHaveCount(0);
  const nav=page.locator('#admin-sidebar nav');await expect(nav.locator('a')).toHaveText(['◈Overview','▦Events','♙Team Members','⌘Domains','↗Join Requests','✉Contact Messages','✦Mail Center','⚙Settings']);
  if(isMobile){await page.getByRole('button',{name:'Menu'}).click();await nav.getByRole('link',{name:'Events',exact:true}).click();await expect(page.locator('#admin-sidebar')).not.toHaveClass(/is-open/);}else await nav.getByRole('link',{name:'Events',exact:true}).click();
  const form=page.locator('#edit-events .new-item').first();await form.locator('summary').click();const title=`Premium workshop ${info.project.name}`;
  await form.getByLabel('Event title').fill(title);await form.getByLabel('Date',{exact:true}).fill('2027-02-12');await form.getByRole('combobox',{name:'Category'}).selectOption('Workshop');await form.getByLabel('Venue / location').fill('Verified test lab');await form.getByLabel('Short introduction').fill('A verified workshop for this isolated browser test.');await form.getByLabel('Full event story').fill('A complete workshop description.\n\n'+('Long event content remains readable. '.repeat(35)));await form.getByLabel('Information source').fill('Isolated browser fixture');await form.getByLabel('Start time').fill('10:30');
  await form.getByLabel('Upload gallery photos').setInputFiles([await imageFile('first.png','#27613a'),await imageFile('second.png','#6baa7e'),await imageFile('third.png','#cfeddb')]);await form.getByRole('button',{name:'Add photos to gallery'}).click();await expect(form.locator('[data-photo-count]')).toContainText('3 / 20');
  const selected=form.locator('[data-photo-option]:has(input:checked)');await expect(selected).toHaveCount(3);const original=await selected.locator('input').evaluateAll(inputs=>inputs.map(input=>input.value));
  if(!isMobile)await selected.first().dragTo(selected.nth(2));else await selected.first().getByRole('button',{name:'Move photo later'}).click();
  await expect.poll(()=>selected.locator('input').evaluateAll(inputs=>inputs.map(input=>input.value))).not.toEqual(original);
  const ordered=await selected.locator('input').evaluateAll(inputs=>inputs.map(input=>input.value));await selected.nth(1).getByRole('button',{name:'Set as cover'}).click();
  await form.getByRole('button',{name:'Create event'}).click();await saved(page);
  let record=page.locator('#edit-events [data-record]').filter({has:page.locator('summary strong',{hasText:title})});await record.locator('summary').click();const id=await record.locator('form').getAttribute('data-id');
  expect((await (await page.request.get('/api/events')).json()).some(e=>e.id===id)).toBe(false);expect((await page.request.get('/admin/events/'+id+'/preview')).status()).toBe(200);
  await record.getByRole('button',{name:'Publish event',exact:true}).click();await confirm(page);await saved(page);
  let published=(await (await page.request.get('/api/events')).json()).find(e=>e.id===id);expect(published.gallery).toEqual(ordered);expect(published.image).toBe(ordered[1]);expect(published.time).toBe('10:30');
  record=page.locator('#edit-events [data-record]').filter({has:page.locator('summary strong',{hasText:title})});await record.locator('summary').click();await record.getByLabel('Venue / location').fill('Updated test venue');await record.locator('[data-photo-option]:has(input:checked)').last().getByRole('button',{name:'Remove photo from event'}).click();await record.getByRole('button',{name:'Save changes'}).click();await saved(page);published=(await (await page.request.get('/api/events')).json()).find(e=>e.id===id);expect(published.location).toBe('Updated test venue');expect(published.gallery).toEqual(ordered.slice(0,2));
  await page.locator('#edit-events [data-record-category]').selectOption('Workshop');await page.locator('#edit-events [data-record-status]').selectOption('published');await expect(page.locator('#edit-events [data-record]:visible')).toHaveCount(1);await page.locator('#edit-events [data-record-from]').fill('2030-01-01');await expect(page.locator('#edit-events > [data-record-list] [data-no-records]')).toBeVisible();await page.locator('#edit-events [data-reset-filters]').click();await page.locator('#edit-events [data-record-sort]').selectOption('newest');await expect(page.locator('#edit-events [data-record]').first()).toContainText(title);
  const search=page.locator('#edit-events [data-record-search]');await search.fill('no such experience');await expect(page.locator('#edit-events > [data-record-list] [data-no-records]')).toBeVisible();await page.locator('#edit-events [data-reset-filters]').click();
  await record.locator('summary').click();await record.getByRole('button',{name:'Unpublish',exact:true}).click();await confirm(page);await saved(page);expect((await (await page.request.get('/api/events')).json()).some(e=>e.id===id)).toBe(false);
  await record.locator('summary').click();await record.getByRole('button',{name:'Delete',exact:true}).click();await page.locator('#confirm-dialog').getByRole('button',{name:'Cancel'}).click();await expect(record).toBeVisible();await record.getByRole('button',{name:'Delete',exact:true}).click();await confirm(page);await saved(page,'Item deleted.');await expect(record).toHaveCount(0);expect(errors).toEqual([]);
});

test('team editing and settings update the public site with real data',async({page},info)=>{
  test.setTimeout(100000);await login(page);await panel(page,'edit-team');const create=page.locator('#edit-team .new-item');await create.locator('summary').click();const name=`Verified Leader ${info.project.name}`;
  await create.getByLabel('Full name').fill(name);await create.getByLabel('Role',{exact:true}).fill('Student coordinator');await create.getByLabel('Introduction').fill('An approved profile for the browser test.');await create.getByLabel('Department',{exact:true}).fill('Computer Science');await create.getByLabel('github URL').fill('https://github.com/example');await create.getByLabel('Add a portrait photo').setInputFiles(await imageFile('portrait.png','#386c4e'));await create.getByLabel(/Published/).check();await create.getByRole('button',{name:'Create member'}).click();await saved(page);
  await page.goto('/team');await page.getByRole('button',{name:'Read about '+name}).click();await expect(page.locator('#detail-dialog')).toContainText('Computer Science');await expect(page.locator('#detail-dialog').getByRole('link',{name:'GitHub'})).toHaveAttribute('href','https://github.com/example');await page.keyboard.press('Escape');
  await panel(page,'edit-team');await page.locator('#edit-team [data-record-search]').fill(name);const record=page.locator('#edit-team [data-record]:visible');await expect(record).toHaveCount(1);await record.locator('summary').click();await record.getByLabel('Role',{exact:true}).fill('Lead coordinator');await record.getByRole('button',{name:'Save changes'}).click();await saved(page);await page.locator('#edit-team [data-record-search]').fill(name);await record.locator('summary').click();await record.getByRole('button',{name:'Delete member'}).click();await confirm(page);await saved(page,'Item deleted.');
  await panel(page,'settings');const settings=page.locator('.settings-form');await settings.getByLabel('Homepage tagline').fill('Approved CIPHER tagline '+info.project.name);await settings.getByLabel('Contact email').fill('cipher-test@example.com');await settings.getByLabel('Verified participants reached').fill('125');await settings.getByLabel('Participant count source').fill('Verified attendance fixture');await settings.getByRole('button',{name:'Save settings'}).click();await saved(page,'Website settings saved.');await page.goto('/');await skip(page);await expect(page.locator('.hero-tagline')).toHaveText('Approved CIPHER tagline '+info.project.name);await expect(page.locator('.public-metrics')).toContainText('Participants reached');await page.goto('/contact');await expect(page.locator('.contact-grid')).toContainText('cipher-test@example.com');
});

test('zero-photo and single-photo events have clean states and long event modals trap focus',async({page},info)=>{
  test.setTimeout(70000);await login(page);const csrf=await page.locator('meta[name="csrf-token"]').getAttribute('content'),headers={'Origin':'http://localhost:3100','X-CSRF-Token':csrf};const ids=[];
  try{
    for(const count of [0,1]){
      const data={title:`Photo state ${count} ${info.project.name}`,date:'2026-03-01',time:'',eventStatus:'completed',category:'Community',location:'Verified test venue',summary:'A verified event for gallery edge cases.',description:'Detailed event information stays readable. '.repeat(140),source:'Browser fixture',image:count?'/images/lumiere.webp':'',gallery:count?['/images/lumiere.webp']:[],published:true};
      const response=await page.request.post('/api/admin/events',{headers,data});expect(response.ok()).toBe(true);const{id}=await response.json();ids.push(id);
      await page.goto('/events/'+id);const gallery=page.locator('[data-stack-gallery]');await expect(gallery.locator('[data-gallery-step],[data-gallery-index],.stack-behind')).toHaveCount(0);
      if(count){await expect(gallery.locator('img')).toHaveCSS('object-fit','cover');await expect.poll(()=>gallery.locator('img').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);}else await expect(gallery).toContainText('Event photographs will be added');
      await page.goto('/#events');const trigger=page.getByRole('button',{name:`View ${data.title} gallery`,exact:true});await trigger.click();const dialog=page.locator('#detail-dialog');await expect(dialog).toBeVisible();await page.locator('#dialog-content').evaluate(el=>el.scrollTop=el.scrollHeight);const close=dialog.getByRole('button',{name:'Close dialog'});await expect(close).toBeVisible();const box=await close.boundingBox();expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(await page.evaluate(()=>innerHeight));
      for(let i=0;i<6;i++){await page.keyboard.press('Tab');expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);}await page.keyboard.press('Escape');await expect(trigger).toBeFocused();await noOverflow(page);
    }
  }finally{for(const id of ids)await page.request.delete('/api/admin/events/'+id,{headers,data:{version:1}});}
});

test('join and contact forms reach separate private workflows; notes, mailing contacts and logout work',async({page},info)=>{
  test.setTimeout(140000);const tag=info.project.name;
  for(const [route,purpose,email] of [['/join','join',`premium-join-${tag}@example.com`],['/contact','contact',`premium-contact-${tag}@example.com`]]){await page.goto(route);await page.getByLabel('Your name').fill('Premium '+purpose+' '+tag);await page.getByLabel('Email address').fill(email);await page.getByLabel('Your message').fill('A real private '+purpose+' message in the isolated test.');await page.getByLabel(/I agree/).check();await page.getByRole('button',{name:'Send message'}).click();await expect(page.locator('#form-status')).toContainText('Message saved successfully.');}
  await login(page);await panel(page,'join-requests');let application=page.locator('#inbox [data-submission]').filter({hasText:`premium-join-${tag}@example.com`});await expect(application).toBeVisible();await application.locator('.message-detail > summary').click();await application.getByLabel('Membership decision').selectOption('reviewed');await application.getByLabel('Private admin notes').fill('Confidential assessment 987');await application.getByRole('button',{name:'Save decision'}).click();await saved(page,'Membership decision saved.');await application.locator('.message-detail > summary').click();await expect(application.getByLabel('Private admin notes')).toHaveValue('Confidential assessment 987');await application.getByLabel('Membership decision').selectOption('selected');await application.getByRole('button',{name:'Save decision'}).click();await saved(page,'Selected member saved.');const savedMember=page.locator('#selected-members [data-saved-member]').filter({hasText:`premium-join-${tag}@example.com`});await expect(savedMember).toBeVisible();
  const bulk=page.locator('#bulk-email-form');await bulk.locator('input[name="subject"]').fill('Approved test message');await bulk.locator('textarea[name="message"]').fill('A message to the saved test membership.');await bulk.getByRole('button',{name:/Preview/}).click();await expect(page.locator('#bulk-addresses')).toContainText(`premium-join-${tag}@example.com`);await page.locator('#send-bulk').click();await saved(page,'Queued for');
  await panel(page,'contact-messages');const message=page.locator('#contact-inbox [data-submission]').filter({hasText:`premium-contact-${tag}@example.com`});await expect(message).toBeVisible();await message.getByRole('button',{name:'Mark as read',exact:true}).click();await saved(page,'Message status updated.');await message.getByRole('button',{name:'Mark as unread'}).click();await saved(page,'Message status updated.');await message.getByRole('button',{name:'Archive message'}).click();await saved(page,'Message status updated.');await expect(message.locator('.badge').first()).toHaveText('Archived');await message.getByRole('button',{name:'Delete message'}).click();await confirm(page);await saved(page,'Enquiry deleted.');await expect(message).toHaveCount(0);
  const home=await (await page.request.get('/')).text();expect(home).not.toContain('Confidential assessment 987');expect(home).not.toContain(`premium-join-${tag}@example.com`);
  if(info.project.name==='mobile')await page.getByRole('button',{name:'Menu'}).click();await page.getByRole('button',{name:'Logout',exact:true}).click();await expect(page).toHaveURL(/\/admin\/login$/);expect((await page.request.get('/api/admin/overview')).status()).toBe(401);await page.goto('/admin');await expect(page).toHaveURL(/\/admin\/login$/);
});
